services:
  - type: web
    name: en-cok-izledigin-oyuncular
    runtime: docker
    plan: free
    region: frankfurt
    repo: https://github.com/kaanguneyli/en-cok-izledigin-oyuncular
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    numInstances: 1
    envVars:
      - key: LETTERBOXD_HOSTED
        value: "1"
      - key: LETTERBOXD_XLSX_BACKEND
        value: xlsxwriter
